# Generated by Django 6.0 on 2025-12-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_category_profile_transaction_delete_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
